package Tela;
import PacienteMetodos.Paciente;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuariod
 */
public class PacienteTela extends javax.swing.JFrame {

    /**
     * Creates new form Paciente
     */
    public PacienteTela() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Panel = new javax.swing.JPanel();
        jLabel1Paciente = new javax.swing.JLabel();
        jLabel1Nome = new javax.swing.JLabel();
        jLabel2Peso = new javax.swing.JLabel();
        jLabel3Altura = new javax.swing.JLabel();
        jTextField1CampoNome = new javax.swing.JTextField();
        jTextField2CampoPeso = new javax.swing.JTextField();
        jTextField3CampoAltura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1CampoArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jComboBox1Sexo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Panel.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1Panel.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1Paciente.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1Paciente.setText("Formulário do Paciente");

        javax.swing.GroupLayout jPanel1PanelLayout = new javax.swing.GroupLayout(jPanel1Panel);
        jPanel1Panel.setLayout(jPanel1PanelLayout);
        jPanel1PanelLayout.setHorizontalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PanelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel1PanelLayout.setVerticalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel1Nome.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1Nome.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1Nome.setText("NOME");

        jLabel2Peso.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2Peso.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2Peso.setText("PESO");

        jLabel3Altura.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3Altura.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3Altura.setText("ALTURA");

        jTextField1CampoNome.setBackground(new java.awt.Color(204, 204, 204));

        jTextField2CampoPeso.setBackground(new java.awt.Color(204, 204, 204));

        jTextField3CampoAltura.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3CampoAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3CampoAlturaActionPerformed(evt);
            }
        });

        jTextArea1CampoArea.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1CampoArea.setColumns(20);
        jTextArea1CampoArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea1CampoArea);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/injecao.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", " " }));
        jComboBox1Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1SexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2Peso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2CampoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jComboBox1Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3Altura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3CampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Nome)
                            .addComponent(jTextField1CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2Peso)
                                    .addComponent(jTextField2CampoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Altura)
                    .addComponent(jTextField3CampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3CampoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3CampoAlturaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField3CampoAlturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Paciente pessoa = new Paciente();
        
        pessoa.setNomeCompleto(jTextField1CampoNome.getText());
        pessoa.setPeso(Integer.parseInt(jTextField2CampoPeso.getText()));
        pessoa.setAltura(Float.parseFloat(jTextField3CampoAltura.getText()));
        pessoa.setSexo((String)jComboBox1Sexo.getSelectedItem());
        
        String saida = "CLÍNICA GYN \n";
        saida = saida + "DADOS DO PACIENTE: \n";
        saida += "NOME COMPLETO: " + pessoa.getNomeCompleto() + "\n";
        saida += "PESO: " + pessoa.getPeso() + "\n";
        saida += "ALTURA: " + pessoa.getAltura() + "\n";
        saida += "SEXO: " + pessoa.getAltura() + "\n";
        saida += "IMC: " + pessoa.calcularIMC() + "\n";
        
        jTextArea1CampoArea.setText(saida);
        jTextField1CampoNome.setText(" ");
        jTextField2CampoPeso.setText(" ");
        jTextField3CampoAltura.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1SexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1Sexo;
    private javax.swing.JLabel jLabel1Nome;
    private javax.swing.JLabel jLabel1Paciente;
    private javax.swing.JLabel jLabel2Peso;
    private javax.swing.JLabel jLabel3Altura;
    private javax.swing.JPanel jPanel1Panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1CampoArea;
    private javax.swing.JTextField jTextField1CampoNome;
    private javax.swing.JTextField jTextField2CampoPeso;
    private javax.swing.JTextField jTextField3CampoAltura;
    // End of variables declaration//GEN-END:variables
}
