package TelaRetangulo;
import RetanguloMetodos.Retangulo;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class RetanguloTela extends javax.swing.JFrame {

    /**
     * Creates new form RetanguloTela
     */
    public RetanguloTela() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Panel = new javax.swing.JPanel();
        jLabel1Retangulo = new javax.swing.JLabel();
        jLabel1Comprimento = new javax.swing.JLabel();
        jLabel2Largura = new javax.swing.JLabel();
        jTextField1Espacocomprimento = new javax.swing.JTextField();
        jTextField2Espacolargura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Campotexto = new javax.swing.JTextArea();
        jButton1Calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Panel.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1Retangulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1Retangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/rectangle1.png"))); // NOI18N
        jLabel1Retangulo.setText("    RETÂNGULO");

        javax.swing.GroupLayout jPanel1PanelLayout = new javax.swing.GroupLayout(jPanel1Panel);
        jPanel1Panel.setLayout(jPanel1PanelLayout);
        jPanel1PanelLayout.setHorizontalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PanelLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1Retangulo)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1PanelLayout.setVerticalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1Retangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel1Retangulo.getAccessibleContext().setAccessibleName("");

        jLabel1Comprimento.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1Comprimento.setText("COMPRIMENTO");

        jLabel2Largura.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2Largura.setText("LARGURA");

        jTextField1Espacocomprimento.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1Espacocomprimento.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jTextField2Espacolargura.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2Espacolargura.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jTextArea1Campotexto.setBackground(new java.awt.Color(255, 204, 204));
        jTextArea1Campotexto.setColumns(20);
        jTextArea1Campotexto.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTextArea1Campotexto.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Campotexto);

        jButton1Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/rectangle.png"))); // NOI18N
        jButton1Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1Comprimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1Espacocomprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2Largura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2Espacolargura, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Comprimento)
                            .addComponent(jTextField1Espacocomprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2Largura)
                            .addComponent(jTextField2Espacolargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CalcularActionPerformed
        // TODO add your handling code here:
        try {
             Retangulo ret = new Retangulo();
             DecimalFormat df = new DecimalFormat("#.00");
        ret.setComprimento(Float.parseFloat(jTextField1Espacocomprimento.getText())); 
        ret.setLargura(Float.parseFloat(jTextField2Espacolargura.getText()));
        String saida = "DADOS DIGITADOS:  \n";
        saida += "COMPRIMENTO: " + df.format(ret.getComprimento()) + "\n";
        saida += "LARGURA: " + df.format(ret.getLargura()) + "\n";
        saida += "CÁLCULO DA ÁREA: " + df.format(ret.calcArea()) + "\n";
        saida += "CÁLCULO DO PERÍMETRO: " + df.format(ret.calcPerimetro()) + "\n";
        jTextArea1Campotexto.setText(saida);
         jTextField1Espacocomprimento.setText(" ");
       jTextField2Espacolargura.setText(" ");
        } catch (Exception erro) {
       JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton1CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetanguloTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetanguloTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetanguloTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetanguloTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetanguloTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Calcular;
    private javax.swing.JLabel jLabel1Comprimento;
    private javax.swing.JLabel jLabel1Retangulo;
    private javax.swing.JLabel jLabel2Largura;
    private javax.swing.JPanel jPanel1Panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Campotexto;
    private javax.swing.JTextField jTextField1Espacocomprimento;
    private javax.swing.JTextField jTextField2Espacolargura;
    // End of variables declaration//GEN-END:variables
}
