/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import Modelo.Cilindro;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class TelaCilindro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCilindro
     */
    public TelaCilindro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Clr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1Cldr2 = new javax.swing.JPanel();
        jLabel2Cldr2 = new javax.swing.JLabel();
        jLabel3Cldr32 = new javax.swing.JLabel();
        jTextField1CampoTxtRaio = new javax.swing.JTextField();
        jTextField2CampoTxtAltura = new javax.swing.JTextField();
        jButton1Executar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Clr.setBackground(new java.awt.Color(51, 255, 153));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cylinder.png"))); // NOI18N
        jLabel1.setText("CILINDRO");

        javax.swing.GroupLayout jPanel1ClrLayout = new javax.swing.GroupLayout(jPanel1Clr);
        jPanel1Clr.setLayout(jPanel1ClrLayout);
        jPanel1ClrLayout.setHorizontalGroup(
            jPanel1ClrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ClrLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel1ClrLayout.setVerticalGroup(
            jPanel1ClrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ClrLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1Cldr2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2Cldr2.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel2Cldr2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2Cldr2.setText("ALTURA");

        jLabel3Cldr32.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel3Cldr32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3Cldr32.setText("RAIO");

        jTextField1CampoTxtRaio.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        jTextField2CampoTxtAltura.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        jButton1Executar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/calculator.png"))); // NOI18N
        jButton1Executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExecutarActionPerformed(evt);
            }
        });

        jTextArea1Info.setColumns(20);
        jTextArea1Info.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jTextArea1Info.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Info);

        javax.swing.GroupLayout jPanel1Cldr2Layout = new javax.swing.GroupLayout(jPanel1Cldr2);
        jPanel1Cldr2.setLayout(jPanel1Cldr2Layout);
        jPanel1Cldr2Layout.setHorizontalGroup(
            jPanel1Cldr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                .addGroup(jPanel1Cldr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jTextField1CampoTxtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2Cldr2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2CampoTxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1Executar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Cldr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3Cldr32)
                    .addContainerGap(823, Short.MAX_VALUE)))
        );
        jPanel1Cldr2Layout.setVerticalGroup(
            jPanel1Cldr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Cldr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Executar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                        .addComponent(jTextField1CampoTxtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Cldr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2Cldr2)
                            .addComponent(jTextField2CampoTxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Cldr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Cldr2Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel3Cldr32)
                    .addContainerGap(232, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Clr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1Cldr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Clr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1Cldr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExecutarActionPerformed
        // TODO add your handling code here:
        try {
            Cilindro cldr = new Cilindro();
            DecimalFormat df = new DecimalFormat("#.00");//ARREDONDAMENTO DE CASAS DECIMAIS
        cldr.setRaio(Float.parseFloat(jTextField1CampoTxtRaio.getText()));
        cldr.setAltura(Float.parseFloat(jTextField2CampoTxtAltura.getText()));
        String saida = "DADOS DIGITADOS: \n";
        saida += "RAIO: " + df.format(cldr.getRaio()) + "\n";
        saida += "ALTURA: " + df.format(cldr.getAltura()) + "\n";
        saida += "CÁLCULO ÁREA LATERAL: " + df.format(cldr.calcAreaLateral()) + "\n";
        saida += "CÁLCULO ÁREA TOTAL: " + df.format(cldr.calcAreaTotal()) + "\n";
        saida += "VOLUME: " + df.format(cldr.calcVolume()) + "\n";
        
        jTextArea1Info.setText(saida);
        jTextField1CampoTxtRaio.setText(" ");
        jTextField2CampoTxtAltura.setText(" ");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }  
    }//GEN-LAST:event_jButton1ExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCilindro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Executar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Cldr2;
    private javax.swing.JLabel jLabel3Cldr32;
    private javax.swing.JPanel jPanel1Cldr2;
    private javax.swing.JPanel jPanel1Clr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Info;
    private javax.swing.JTextField jTextField1CampoTxtRaio;
    private javax.swing.JTextField jTextField2CampoTxtAltura;
    // End of variables declaration//GEN-END:variables
}
