/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import Metodos.Esfera;
import java.text.DecimalFormat;
import javax.swing.JOptionPane; 
/**
 *
 * @author Usuario
 */
public class TelaEsfera extends javax.swing.JFrame {

    /**
     * Creates new form TelaEsfera
     */
    public TelaEsfera() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Panel = new javax.swing.JPanel();
        jLabel1Esfera = new javax.swing.JLabel();
        jLabel1Raio = new javax.swing.JLabel();
        jTextField1ValoRaio = new javax.swing.JTextField();
        jButton2Calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1CampoArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Panel.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1Esfera.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1Esfera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sphere.png"))); // NOI18N
        jLabel1Esfera.setText("      ESFERA");

        javax.swing.GroupLayout jPanel1PanelLayout = new javax.swing.GroupLayout(jPanel1Panel);
        jPanel1Panel.setLayout(jPanel1PanelLayout);
        jPanel1PanelLayout.setHorizontalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1Esfera, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel1PanelLayout.setVerticalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1PanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1Esfera, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jLabel1Raio.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1Raio.setText("RAIO");

        jTextField1ValoRaio.setBackground(new java.awt.Color(204, 204, 204));

        jButton2Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/measure.png"))); // NOI18N
        jButton2Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CalcularActionPerformed(evt);
            }
        });

        jTextArea1CampoArea.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea1CampoArea.setColumns(20);
        jTextArea1CampoArea.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jTextArea1CampoArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea1CampoArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1Raio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1ValoRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Raio)
                            .addComponent(jTextField1ValoRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton2Calcular)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CalcularActionPerformed
        // TODO add your handling code here:
        try {
            DecimalFormat df = new DecimalFormat("#.00");
         Esfera esferaa = new Esfera();
         esferaa.setRaio(Float.parseFloat(jTextField1ValoRaio.getText()));  
         String saida = "Dados da esfera \n";
         saida += "Raio: " + df.format(esferaa.getRaio()) +  "\n";
         saida += "Área Total: " + df.format(esferaa.calcAreaEsfera()) + "\n";
         saida += "Volume: " + df.format(esferaa.calcVolumeEsfera()) + "\n";
         jTextArea1CampoArea.setText(saida);
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage());
        }
        jTextField1ValoRaio.setText(" ");
    }//GEN-LAST:event_jButton2CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEsfera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEsfera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2Calcular;
    private javax.swing.JLabel jLabel1Esfera;
    private javax.swing.JLabel jLabel1Raio;
    private javax.swing.JPanel jPanel1Panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1CampoArea;
    private javax.swing.JTextField jTextField1ValoRaio;
    // End of variables declaration//GEN-END:variables
}
