/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import Modelo.Cone;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class TelaCone extends javax.swing.JFrame {

    /**
     * Creates new form TelaCone
     */
    public TelaCone() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextArea1Saidadados.setEditable(false);//IMPEDIR QUE SE DIGITA NA AREA DE TEXTO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Cima = new javax.swing.JPanel();
        jLabel1Cone = new javax.swing.JLabel();
        jPanel2Baixo = new javax.swing.JPanel();
        jLabel1Raio = new javax.swing.JLabel();
        jLabel2Altura = new javax.swing.JLabel();
        jTextField1CampoTxtRaio = new javax.swing.JTextField();
        jTextField2CampoTxtAltura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Saidadados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Cima.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1Cone.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        jLabel1Cone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/cone.png"))); // NOI18N
        jLabel1Cone.setText("CONE");

        javax.swing.GroupLayout jPanel1CimaLayout = new javax.swing.GroupLayout(jPanel1Cima);
        jPanel1Cima.setLayout(jPanel1CimaLayout);
        jPanel1CimaLayout.setHorizontalGroup(
            jPanel1CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1CimaLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1Cone, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1CimaLayout.setVerticalGroup(
            jPanel1CimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1CimaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1Cone)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jPanel2Baixo.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1Raio.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel1Raio.setText("RAIO");

        jLabel2Altura.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel2Altura.setText("ALTURA");

        jTextField1CampoTxtRaio.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1CampoTxtRaio.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        jTextField2CampoTxtAltura.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2CampoTxtAltura.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/calculator.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1Saidadados.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1Saidadados.setColumns(20);
        jTextArea1Saidadados.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jTextArea1Saidadados.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Saidadados);

        javax.swing.GroupLayout jPanel2BaixoLayout = new javax.swing.GroupLayout(jPanel2Baixo);
        jPanel2Baixo.setLayout(jPanel2BaixoLayout);
        jPanel2BaixoLayout.setHorizontalGroup(
            jPanel2BaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2BaixoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2BaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2BaixoLayout.createSequentialGroup()
                        .addComponent(jLabel1Raio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1CampoTxtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(697, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2BaixoLayout.createSequentialGroup()
                        .addComponent(jLabel2Altura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2CampoTxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(460, 460, 460)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
            .addGroup(jPanel2BaixoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2BaixoLayout.setVerticalGroup(
            jPanel2BaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2BaixoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2BaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2BaixoLayout.createSequentialGroup()
                        .addGroup(jPanel2BaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Raio)
                            .addComponent(jTextField1CampoTxtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2BaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2Altura)
                            .addComponent(jTextField2CampoTxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Cima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2Baixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Cima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2Baixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Cone cn = new Cone();
            DecimalFormat df = new DecimalFormat("#.00");
        cn.setRaio(Float.parseFloat(jTextField1CampoTxtRaio.getText()));
        cn.setAltura(Float.parseFloat(jTextField2CampoTxtAltura.getText()));
        String saida = "DADOS DIGITADOS: \n";
        saida += "RAIO: " + df.format(cn.getRaio()) + "\n";
        saida += "ALTURA: " + df.format(cn.getAltura()) + "\n";
        saida += "CÁLCULO DA GERATRIZ: " + df.format(cn.calcGeratriz()) + "\n";
        saida += "CÁLCULO DA ÁREA LATERAL: " + df.format(cn.calcAreaLateral()) + "\n";
        saida += "CÁLCULO DA ÁREA TOTAL: " + df.format(cn.calcAreaTotal()) + "\n";
        saida += "VOLUME: " + df.format(cn.calcVolume()) + "\n";
        jTextArea1Saidadados.setText(saida);
        jTextField1CampoTxtRaio.setText(" ");
        jTextField2CampoTxtAltura.setText(" ");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
        
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1Cone;
    private javax.swing.JLabel jLabel1Raio;
    private javax.swing.JLabel jLabel2Altura;
    private javax.swing.JPanel jPanel1Cima;
    private javax.swing.JPanel jPanel2Baixo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Saidadados;
    private javax.swing.JTextField jTextField1CampoTxtRaio;
    private javax.swing.JTextField jTextField2CampoTxtAltura;
    // End of variables declaration//GEN-END:variables
}
